//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.04 at 01:44:06 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:callcenter.eppic.tps.com")
package com.conduent.siebel.usps.address.jaxb;
